Repository freeCodeCamp-China/Web-site, pull requests merged in 2023-08, with the labels that each got.

#19 [optimize] main Nav Bar style
  components/MainNavigator.tsx
  styles/MainNavigator.module.less
Labels: bug

#20 feat: refactoring organizational components
  components/MainNavigator.tsx
  components/PersonCard.tsx
  old/organiser.html
  old/organiser.js
  pages/api/data.ts
  pages/api/organizer.ts
  pages/organizer/[name].tsx
  pages/organizer/index.tsx
  public/image/organizer/caiting.png
  public/image/organizer/chencanbin.png
  public/image/organizer/chenjie.png
  public/image/organizer/chenqinchao.png
  public/image/organizer/chenxiaoshan.png
  public/image/organizer/chenzhicheng.png
  public/image/organizer/fengbo.png
  public/image/organizer/fengzhongmei.png
  public/image/organizer/hanyile.png
  public/image/organizer/heqingsong.png
  public/image/organizer/huangjinliang.png
  public/image/organizer/jiangyuzhen.png
  public/image/organizer/kanziqiang.png
  public/image/organizer/lanhao.png
  public/image/organizer/liangcaiyi.png
  public/image/organizer/lindongwen.png
  public/image/organizer/liningchuan.png
  public/image/organizer/liubo.png
  public/image/organizer/liudong.png
  public/image/organizer/liunanbin.png
  public/image/organizer/liuqianyu.png
  public/image/organizer/liuzhu.png
  public/image/organizer/lixukai.png
  public/image/organizer/manyuanrong.png
  public/image/organizer/qianyu.png
  public/image/organizer/shiyao.png
  public/image/organizer/tangxiaofang.png
  public/image/organizer/tangyouhua.png
  public/image/organizer/wangbo.png
  public/image/organizer/wangchuan.png
  public/image/organizer/wangdong.png
  public/image/organizer/wangjie.png
  public/image/organizer/wangjun.png
  public/image/organizer/wangshengsong.png
  public/image/organizer/weichaoxin.png
  public/image/organizer/wuyanan.png
  public/image/organizer/wuyuping.png
  public/image/organizer/xiejiaqi.png
  public/image/organizer/xuekaiqi.png
  public/image/organizer/yilina.png
  public/image/organizer/yinting.png
  public/image/organizer/youshoujie.png
  public/image/organizer/yuanmincheng.png
  public/image/organizer/yuhang.png
  public/image/organizer/yuqi.png
  public/image/organizer/zengchangqiang.png
  public/image/organizer/zhangfengtao.png
  public/image/organizer/zhangxiaobai.png
  public/image/organizer/zhengmengyu.png
  public/image/organizer/zhuxiaopeng.png
Labels: feature

#22 feat: ConferencePage compoments : conferenceSchedule
  components/conference/CityScheduleInfo.module.less
  components/conference/CityScheduleInfo.tsx
  components/conference/Guest.module.less
  components/data/CitySchedulesData.json
  pages/conference.tsx
Labels: enhancement

#29 [optimize] Using Carousel to display images ; Fix title id misplaced ; update favicon.ico ,update SITE_NAME ,SUMMARY
  .env
  components/conference/ConferenceBase.module.less
  components/conference/ConferenceBase.tsx
  components/conference/Guest.tsx
  components/conference/Organization.tsx
  public/favicon.ico
Labels: bug

#23 [migrate] replace Scaffold Built-in middleware with Next SSR middleware
  components/BlockEditor.tsx
  components/HTMLEditor.tsx
  package.json
  packages.d.ts
  pages/api/core.ts
  pages/component.tsx
  pages/conference.tsx
  pages/index.tsx
  pages/pagination.tsx
  pages/scroll-list.tsx
  pnpm-lock.yaml
Labels: enhancement

#32 [fix] responsive layout for city index and detail city page
  components/CommunityCityList.tsx
  components/PersonCard.tsx
  components/conference/Guest.tsx
  pages/city/[city].tsx
  pages/organizer/index.tsx
Labels: enhancement

#38 Optimization : conference page and organizer page layout ; fix build error
  components/Git/Logo.tsx
  components/PageHead.tsx
  components/conference/CityScheduleInfo.module.less
  components/conference/CityScheduleInfo.tsx
  components/conference/ConferenceBase.tsx
  components/conference/Organization.module.less
  components/conference/Organization.tsx
  data/conference/CitySchedulesData.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/organizer/[name].tsx
  pnpm-lock.yaml
  styles/globals.less
Labels: enhancement
